### ISSUE TITLE
Beta release NuGet Package doesn't include the zeromq dll's required to run. 

### ISSUE THREAD

**Issue by staticcat** [zeromq/clrzmq#100]
The system when run up trying to create a context says that is fails to load a context. The reason for the failure is because "libzmq.dll" was not found on the system. Sure enough its not anywhere and has to included manually. 

Main point of NuGet is removing the need to manage dll's directly.

**Comment by staticcat** [comment]
I see that libzmq.3.2.1-beta2 is a package used by the clrzmq solution in the depot. Also there is a libzmq.nuspec located in the solution to release a NuGet package for the library. 

From all this is seems that the plan would be to release the packages together and make clrzmq depend on libzmq. Is this correct?

**Comment by jgoz** [comment]
The NuGet package (actually, `clrzmq.dll` itself) _does_ include `libzmq.dll`. In fact, it includes both 32-bit and 64-bit versions as manifest resources and extracts the correct library for the running platform at app startup (in a static context).

You may be seeing this particular issue because of #99. The bundled `libzmq.dll` libraries in the latest NuGet release were accidentally built with VS2012, so they require the [latest VC++ redistributable](http://www.microsoft.com/en-us/download/details.aspx?id=30679). If you are using your own libzmq.dll, it has to be manually deployed alongside clrzmq.dll or somewhere on the system path.

I will be fixing the bundled libzmq.dll files with the next release so that they only depend on the VC++ 2010 redistributable, as before.

**Comment by jgoz** [comment]
I've fixed the VC++ redistributable dependency with the latest release pushed to NuGet. Let me know if you experience the same issue.

**Comment by staticcat** [comment]
Awesome thanks will check this ASAP.

**Comment by staticcat** [comment]
Updated my local solutions and its working fine.
