### ISSUE TITLE
"ZMQ.Exception: The Address is already in use" for no reason

### ISSUE THREAD

**Issue by nilsh** [zeromq/clrzmq#28]
I'm getting this error sporadically. Everytime i get this Error, i've checked if there is another process which is already listening on that port, it was never the case.

On the same system at the same time i've had some "too many open files" problems, so that may be the real reason.

Since i'm using zeromq with clrzmq2 i've always got misleading error messages from it. There is much room for improvement.

**Comment by jgoz** [comment]
Sorry for the long delay on responding to this issue. Are you still experiencing the problems you described?

If so, I have a few questions that may help diagnose the issue:
1. Are you using .NET/Win or Mono/Posix?
2. What transport are you using (I'm assuming TCP, since you mentioned ports)?
3. Are all of your sockets inside the same Context & process?
4. How many sockets are you dealing with?
5. Are the "too many open files" errors caused by your application?
6. How often and under what conditions do you see this error? e.g., Only when starting the app, 10% of the time.
7. What version of libzmq are you using?

**Comment by nilsh** [comment]
Hi jgoz, currently i am not able to re-produce the error as my former environment doesn't exist anymore, so i'm closing this..
