### ISSUE TITLE
Server freezes when there's no response

### ISSUE THREAD

**Issue by laxx** [zeromq/clrzmq#31]
I noticed every time I load a page that's making a request to an address, the server seems to freeze whenever there is no response/data from the address. Is this a bug or am I doing something wrong here? here's my code:

```
    ZMQ.Context context = new ZMQ.Context(1);
    ZMQ.Socket socket = context.Socket(ZMQ.SocketType.DEALER);
    socket.Connect("address_goes_here");
    socket.Recv();
```

**Comment by jgoz** [comment]
That is the expected behaviour. The `socket.Recv()` call will block the calling thread until a response is received.

If you wish to make it non-blocking, use one of the overloads to specify a timeout value. You can also pass `SendRecvOpt.NOBLOCK` as a parameter, which will cause it to return immediately if there is nothing to receive.

I'm going to close this issue for now, but you are welcome to re-open it if you still have problems with a non-blocking Recv call.
