### ISSUE TITLE
Constructor Socket(SocketType type) should be removed

### ISSUE THREAD

**Issue by fholm** [zeromq/clrzmq#38]
I feel that the `public Socket(SocketType type)` should be removed, and the entire idea of "_appContext" is just weird and can give odd (and hard to debug) behavior if you by accident use the _appContext at some point even though you have your own context setup.

And even though I have limited knowledge of ZMQ, i can't find any reference to an "app context" in ZMQ that it would default to.

**Comment by jgoz** [comment]
As I commented in #37, this would be a breaking change and will have to be deferred until v3, even though I agree with you completely.

I believe the concept for this static, app-wide Context object was introduced by the old maintainer and was borrowed from an alternate set of bindings. The concept is probably unique to these bindings and, as you stated, is somewhat dangerous. Context management should be explicit; it would be much better for developers to use DI for managing the lifetime scope of the Context instead of this.

The best I can do right now is to add an `[Obsolete]` tag to this constructor with a message indicating that context management should be explicit.

Have a look at my [experimental bindings](https://github.com/jgoz/netzmq) if you get a chance. I will probably borrow some ideas for clrzmq v3 from this API.
