### ISSUE TITLE
Socket.Address issue

### ISSUE THREAD

**Issue by frichard** [zeromq/clrzmq#44]
I have this case where I am binding a socket of type SocketType.REP to multiple listening point and it works, but the Address property does not really support multiple binds.

Here is the example:

``` csharp
  using (Socket socket = _context.Socket(SocketType.REP))
  {
    s_log.DebugFormat("ZMQ Version: {0}", ZMQ.ZHelpers.Version());
    socket.Bind(BindAddress);  // tcp://*:5555
    socket.Bind(InprocInternalstop); // inproc://internalstop
     s_log.DebugFormat("ZMQ bindAddress {0}", socket.Address);
    (...)
```

And will produce the following log output:

DEBUG Xobni.CoreWorkers.JobsReceiver (null) - ZMQ Version: 2.1.11
DEBUG Xobni.CoreWorkers.JobsReceiver (null) - ZMQ bindAddress inproc://internalstop

Should the Address property actually be a List of Strings ?

**Comment by jgoz** [comment]
You are correct, `Address` will only contain the last bound address ([relevant source](https://github.com/zeromq/clrzmq/blob/2.2/src/clrzmq/Socket.cs#L359)).

The problem I have with extending this property to support multiple addresses is more that I'm not sure this property is all that useful in the first place. Since it only returns the exact address supplied by the application (vs. somehow getting the address from the underlying socket), the application should already know which addresses the socket is bound to. If `Bind` fails, it throws an exception, so you can be sure that multiple successful calls to `Bind` will have bound the socket to the given addresses.

Your example could realistically be changed to the following:

``` C#
using (Socket socket = _context.Socket(SocketType.REP))
{
    s_log.DebugFormat("ZMQ Version: {0}", ZMQ.ZHelpers.Version());

    socket.Bind(BindAddress); // tcp://*:5555
    s_log.DebugFormat("ZMQ bindAddress {0}", BindAddress);

    socket.Bind(InprocInternalstop); // inproc://internalstop
    s_log.DebugFormat("ZMQ bindAddress {0}", InprocInternalstop);
    (...)
}
```

It would be different if you could bind to a random port or inproc address, for instance, and have `Address` return the resulting address, but it does not work like this, nor is there a mechanism in ZeroMQ for such functionality.

Are there other situations in which retrieving the bound addresses would be useful to you? If you needed this information sometime after socket initialization, it might be different, but I'm having trouble visualizing such a scenario.

**Comment by sustrik** [comment]
Agreed with the above. No point in polluting the API with functions with little or no value for the user.

**Comment by jgoz** [comment]
I'm closing this request for now. If @frichard has a compelling case for tracking multiple bind addresses, I'd be happy to hear it and reopen if necessary.
