### ISSUE TITLE
ZMQDevice.AsyncReturn.Dispose() hangs

### ISSUE THREAD

**Issue by skradel** [zeromq/clrzmq#57]
Calling .Dispose() without first calling .Stop() and .DoneEvent.WaitOne() always hangs, making it impossible to apply regular IDisposable conventions; tested on 2.2.2 and 2.2.3 x86.

**Comment by jgoz** [comment]
I think I know what the problem is, and it affects every Device including the AsyncReturn.

The following block in `Device.Dispose(bool)` has a bug:

``` c#
if (_isRunning) {
    Stop();
    while (_isRunning) { Thread.Sleep((int)PollingInterval); }
}
```

`PollingInterval` is set to 750000 because in ZMQ 2.x, `zmq_poll` takes uses microsecond precision, but Thread.Sleep uses millisecond precision. This causes it to hang for 12.5 minutes while waiting for confirmation that the device has stopped. I guess that's a bit too long :)

**Comment by skradel** [comment]
I'd advise not to Sleep(int) explicitly at all as these tend to add up in a large program -- there is already a WaitHandle there to use.  e.g.:

``` C#
if (_isRunning) 
{
    Stop();
    if (!DoneEvent.WaitOne(1000))
    {
        // this is taking a really long time!  exception?
    }
}
```

**Comment by jgoz** [comment]
Good call! I think that Sleep call was in there a couple years before the MRE got added. I'm all for getting rid of explicit Sleeps.
