### ISSUE TITLE
clrzmq should target the .NET 2.0/3.5 framework

### ISSUE THREAD

**Issue by bassam** [zeromq/clrzmq#59]
.NET 4.0 is not widely deployed, and it reduces the adoption of this binding. It looks like the 2.2 branch is on the 2.0/3.5 profile.

**Comment by jgoz** [comment]
I presume you're talking about the master branch (v3.x).

I disagree with you on this one. .NET 4.0 has been available since April 2010, which means we've had exactly two full years to make a key infrastructure upgrade, which IMO is plenty of time. Also, .NET 4.5 is right around the corner.

Adding .NET 2.0/3.5 support back into the v3.x unstable branch would mean introducing more complexity by way of #ifdefs. I'd also have to package two release streams, one for 2.0/3.5 and one for 4.0. As you pointed out, v2.x targets 2.0/3.5, so those who are stuck on older runtimes are still able to use clrzmq.

Anyway, sorry to shoot the idea down, but I don't believe maintaining support for old runtimes makes sense for the unstable branch.

**Comment by mkoppanen** [comment]
Looks like clrzmq-old has been removed and projects targeting v3.5 framework don't have available bindings.

**Comment by jgoz** [comment]
> Looks like clrzmq-old has been removed and projects targeting v3.5 framework don't have available bindings.

The v2.2/stable branch of clrzmq still targets .NET 2.0 & 3.5, so this statement is incorrect.

Support for old .NET frameworks will not be added to the master (v3.x) branch.
