### ISSUE TITLE
warning CS0618: 'ZeroMQ.SocketType.XREQ' is obsolete: 'This socket type will be removed in a future release.'

### ISSUE THREAD

**Issue by rohitjoshi** [zeromq/clrzmq#85]
I am getting this warning. What is the replacement for XREQ? SocketType.REQ ?

**Comment by tjrobinson** [comment]
I believe it's the equivalent of ZMQ_DEALER:

"A socket of type ZMQ_DEALER is an advanced pattern used for extending request/reply sockets. Each message sent is round-robined among all connected peers, and each message received is fair-queued from all connected peers."

"When a ZMQ_DEALER socket enters an exceptional state due to having reached the high water mark for all peers, or if there are no peers at all, then any zmq_send(3) operations on the socket shall block until the exceptional state ends or at least one peer becomes available for sending; messages are not discarded."

"When a ZMQ_DEALER socket is connected to a ZMQ_REP socket each message sent must consist of an empty message part, the delimiter, followed by one or more body parts."

"Deprecated alias: ZMQ_XREQ."

http://api.zeromq.org/3-3:zmq-socket

**Comment by jgoz** [comment]
@tjrobinson is correct.

If you inspect the [source](https://github.com/zeromq/clrzmq/blob/master/src/ZeroMQ/SocketType.cs#L99), you'll see that `XREP` is an alias for `DEALER`.

I will change the Obsolete message to explicitly reference the correct socket type.
